services:
  - type: web
    name: dynamic-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: AVIATIONSTACK_API_KEY
        sync: false
      - key: ADMIN_KEY
        sync: false

  - type: web
    name: dynamic-frontend
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_ORIGIN
        fromService:
          type: web
          name: dynamic-backend
          property: url
